config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :neighbors_settings, only: [:edit, :update] do
      member do
        get :add_neighbor
        delete :delete_neighbor
      end
    end


    resources :products do
      member do
        get :neighbors
      end
    end

    resources :neighbors, only: [:destroy, :create]
  end
end

app/models/spree/neighbors_settings.rb
class Spree::NeighborsSettings < ActiveRecord::Base
  belongs_to :location, class_name: "Spree::Location"
  validates :radius, :numericality => { :greater_than_or_equal_to => 0 }
  validates :count, :numericality => { :greater_than_or_equal_to => 0, only_integer: true }
  validates :sort, :numericality => { :greater_than_or_equal_to => 0, only_integer: true }
  has_many :neighbors, class_name: "Spree::Neighbors"
  has_one :neighbors_by_property, class_name: "Spree::NeighborsByProperty"

  def self.create_settings_for(location)
    s = Spree::NeighborsSettings.new
    s.location_id = location.id
    s.radius = 10
    s.count = 10
    s.sort = 1
    s.save
  end
end

app/controllers/spree/admin/neighbors_settings_controller.rb
module Spree
  module Admin
    class NeighborsSettingsController < Spree::Admin::BaseController

      def edit
        page   = (params[:page] || 1).to_i
        per    = (params[:per] || Spree::Config[:admin_products_per_page]).to_i
        @collection = Spree::Location.includes(:locatable => :translations)
        @collection = @collection.where(:locatable_id => Spree::Product.all.pluck(:id))
        @collection = @collection.page(page).per(per)
      end

      def update
        neighbors_quantity = params[:quantity_active] == '1' ? (Integer(params[:neighbors_quantity]) > 0 ? Integer(params[:neighbors_quantity]) : 0) : 0
        neighbors_sorting = params[:sorting_active] == '1' ? (Integer(params[:sort]) > 0 ? Integer(params[:sort]) : 0) : 0
        neighbors_setting = Spree::NeighborsSettings.find(params[:neighbors_setting_id])
        radius = params[:radius_active] == '1' ? (Float(params[:radius]) > 0 ? Float(params[:radius]) : 0) : 0

        property_id = params[:properties_active] == '1' ? params[:property_id] : '0'
        property_value = params[:properties_active] == '1' ? params[:property_value] : ""

        neighbors_setting.neighbors_by_property ||= Spree::NeighborsByProperty.new()
        neighbors_setting.neighbors_by_property.property_id = property_id
        neighbors_setting.neighbors_by_property.value = property_value

        neighbors_setting.radius = radius
        neighbors_setting.count = neighbors_quantity
        neighbors_setting.sort = neighbors_sorting
        neighbors_setting.neighbors_by_property.save()

        if neighbors_setting.save()
          flash[:success] = t(:successfully_updated_settings)
        else
          flash[:error] = t(:fail_updated_settings)
        end

        redirect_to :back
      end

    end
  end
end

app/helpers/spree/admin/neighbors_settings_helper.rb
module Spree
  module Admin
    module NeighborsSettingsHelper

      def get_name_from_locatable(item)
        item.locatable.name
      end

      def try_set_neighbor_settings_for_locatable(item)
        item.neighbors_settings = item.neighbors_settings || Spree::NeighborsSettings.create(:location_id => item.id)
      end

      def get_neighbors_pins_coordinates(item)
        neighbors_settings = item.neighbors_settings
        unless neighbors_settings.nil?

          neighbors_ids = Spree::Neighbors.where(neighbors_settings_id: neighbors_settings.id).map { |neighbor| neighbor.location_id}
          nearby_items = neighbors_settings.radius > 0 ? Spree::Location.where(locatable_type: item.locatable_type).where.not(id: item.id).where.not(id: neighbors_ids).near([item.latitude, item.longitude], neighbors_settings.radius).map { |locatable| {:latitude => locatable.latitude, :longitude => locatable.longitude, :distance => item.distance_from([locatable.latitude, locatable.longitude]), :locatable_id => locatable.id } } : []
          neighbors = Spree::Neighbors.where(neighbors_settings_id: neighbors_settings.id).map { |neighbor| {:latitude => neighbor.location.latitude, :longitude => neighbor.location.longitude, :distance => item.distance_from([neighbor.location.latitude, neighbor.location.longitude]), :locatable_id => neighbor.location.id } }
          products_prop = neighbors_settings.neighbors_by_property.nil? ? [] : neighbors_settings.neighbors_by_property.value == "" ? [] : Spree::ProductProperty.where(property_id: item.neighbors_by_property.property_id, value: item.neighbors_by_property.value).map{ |product_prop| product_prop.product }
          neighbors_by_prop = []
          products_prop.each do |prod|
            unless prod.location.nil?
              neighbors_by_prop << {:latitude => prod.location.latitude, :longitude => prod.location.longitude, :distance => item.distance_from([prod.location.latitude, prod.location.longitude]), :locatable_id => prod.location.id }
            end
          end

        end
        #The sorting bussiness goes here
        result = nearby_items + neighbors + neighbors_by_prop
        sorted = result.sort_by { |item| item[:distance] }
        final_result = sorted

        if neighbors_settings.count > 0
          #it does'nt matter if the count is bigger than the amount of items it gets them all
          final_result = sorted.take(neighbors_settings.count)
        end

        final_result

      end

    end
  end
end

app/views/spree/admin/neighbors_settings/_add_neighbors.html.erb
<script type="text/javascript">
$().ready(function(){
  $('#s2id_neighbor_product .select2-chosen').html("");
  $('#add_neighbor_button').click(function(){
    selected_item = $('#s2id_neighbor_product .select2-chosen').text();
    if (selected_item != "") {
      $('#s2id_neighbor_product .select2-chosen').html("");
    };
  });

  var quantity_active = <%= @neighbors_settings.count > 0 ? '1' : '0' %>;
  var radius_active = <%= @neighbors_settings.radius > 0 ? '1' : '0' %>;
  var sorting_active = <%= @neighbors_settings.sort > 0 ? '1' : '0' %>;
  var properties_active = <%= @property_selected_value != "" ? '1' : '0' %>;

  if (<%= @property_selected %> == 0) {
    $('#s2id_property_id .select2-chosen').html("");
  };

  if (<%= @sorting_selected %> == 0) {
    $('#s2id_sort .select2-chosen').html("");
  };

  if (quantity_active == '1') {
    $('#quantity_active').click();
  };
  if (radius_active == '1') {
    $('#radius_active').click();
  };

  if (properties_active == '1') {
    $('#properties_active').click();
  };

  if (sorting_active == '1') {
    $('#sorting_active').click();
  };

});
</script>

app/views/spree/admin/neighbors_settings/_locatable.html.erb
<div class="alpha twelve columns">
  <%= form_tag(admin_neighbors_settings_path, :method => :put) do %>
    <fieldset>
      <legend align="center"><%= t(:show_neighbors_that) %></legend>
        <div class="row">
          <%= check_box_tag(:quantity_active)%>
          <%= label_tag(:quantity_active, t(:show_only)) %>
          <%= number_field_tag :neighbors_quantity, @neighbors_settings.count, class: 'neighbors-number-field', :min => 0 %>
          <%= label_tag(:radius, t(:neighbors)) %>
          <%= hidden_field_tag(:neighbors_setting_id, @neighbors_settings.id) %>
        </div>
        <div class="row">
          <%= check_box_tag(:radius_active)%>
          <%= label_tag(:radius_active, t(:neighbors_within)) %>
          <%= number_field_tag :radius, @neighbors_settings.radius, class: 'neighbors-number-field', :min => 0 %>
          <%= label_tag(:radius, t(:range)) %>
        </div>
        <div class="row">
          <%= check_box_tag(:properties_active) %>
          <%= label_tag(:properties_active, t(:neighbors_with_property)) %>
          <%= select_tag 'property_id', options_for_select(@properties, @property_selected), class: 'select2' %>
          <%= label_tag(:property_value, t(:with_value)) %>
          <%= text_field_tag :property_value, @property_selected_value%>
        </div>
        <div class="row">
          <%= check_box_tag(:sorting_active) %>
          <%= label_tag(:sorting_active, t(:sort_neighbors_by)) %>
          <%= select_tag 'sort', options_for_select(@sorting_options, @sorting_selected), class: 'select2' %>
        </div>
        <div id="hidden_fields"></div>
        <div class="form-buttons filter-actions actions" data-hook="buttons">
          <%= button Spree.t('actions.update'), 'icon-refresh' %>
          <span class="or"><%= Spree.t(:or) %></span>
          <%= link_to_with_icon 'icon-remove', Spree.t('actions.cancel'), collection_url, :class => 'button' %>
        </div>
    </fieldset>
  <% end %>
  <fieldset>
    <legend align="center"><%= t(:add_neighbors) %></legend>
    <div class="row">
      <div class="five column">
        <%= form_tag(admin_neighbors_url, :method => :post, :remote => true) do %>
          <%= hidden_field_tag(:neighbors_settings_id, @neighbors_settings.id) %>
          <%= label_tag :neighbor_product, t(:neighbor_product) %>
          <%= select_tag 'neighbor_product', options_for_select(@locatables), class: 'select2' %>
          <button class="icon-plus button" name"add_neighbor" id="add_neighbor_button">Add Neighbor</button>
        <%end%>
      </div>
    </div>

    <% if @neighbors_locatables.any? %>
    <table class="index locatables-items" id="listing_locatables">
      <colgroup>
         <col style="width: 80%;">
         <col style="width: 20%;">
      </colgroup>
      <thead>
        <tr data-hook="admin_locatables_index_headers">
          <th><%= Spree.t(:name) %></th>
          <th data-hook="admin_locatables_index_header_actions" class="actions"></th>
        </tr>
      </thead>
      <tbody>
        <% @neighbors_locatables.each do |locatable| %>
            <tr id="<%=locatable[1]%>" data-hook="admin_locatables_index_rows" class="<%= cycle('odd', 'even') %>">
              <td><%= locatable[0] %></td>
              <td class="actions" data-hook="admin_locatables_index_row_actions">
                <a class="delete-resource icon_link with-tip icon-trash no-text neighbors_delete_icon" data-action="remove" data-confirm="Are you sure?" href="<%= admin_neighbor_path(locatable[2]) %>">​</a>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="no-objects-found">
      <%= t(:no_neighbors) %>
    </div>
  <% end %>
  </fieldset>
</div>

<%= neighbors_map(@neighbors_settings.location.locatable) %>
<ul id="neighbors-list">
<% products_neighbors(@neighbors_settings.location.locatable).each do |neighbor| %>
  <li><%= link_to neighbor.try(:name), product_path(neighbor) %></li>
<%end%>
</ul>

<%= render :partial => 'spree/admin/neighbors_settings/add_neighbors' %>

app/views/spree/admin/neighbors_settings/edit.html.erb
<% content_for :page_title do %>
  <%= t(:spree_neighbors_settings) %>
<% end %>
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% if @collection.any? %>
  <table class="index locatables-items" id="listing_locatables">
    <colgroup>
       <col style="width: 78%;">
       <col style="width: 22%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_locatables_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th data-hook="admin_locatables_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |locatable| %>
          <tr id="<%= spree_dom_id locatable %>" data-hook="admin_locatables_index_rows" class="<%= cycle('odd', 'even') %>">
            <td><%= get_name_from_locatable(locatable)%></td>
            <td class="actions" data-hook="admin_locatables_index_row_actions">
              <%= link_to_edit_url edit_admin_neighbors_settings_url, :no_text => true, :class => 'edit' %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= Spree.t(:no_results) %>
  </div>
<% end %>

<%= paginate @collection %>